/**
 * THIS IS AN AUTOGENERATED FILE, YOU SHOULD NOT MODIFY IT MANUALLY
 * TO REGENERATE THIS FILE RUN `NPM RUN CODEGEN`.
 */
import { CustomTheme } from 'azure-iot-fluent-css';
export declare function createCustomThemeStylesheet(theme: CustomTheme): string;
export declare function clearThemeProperties(DOMElement: HTMLElement): void;
