/**
 * THIS IS AN AUTOGENERATED FILE, YOU SHOULD NOT MODIFY IT MANUALLY
 * TO REGENERATE THIS FILE RUN `NPM RUN CODEGEN`.
 */
import { CustomTheme } from './themeTypes';
export declare const DefaultThemes: {
    [theme: string]: CustomTheme;
};
